trigger:
  - master
variables:
  - group: UiPath
  - name: agent.preferPowerShellOnContainers
    value: "True"

stages:
  - stage: Build
    displayName: Create build artifact
    jobs:
      - job: BuildArtifact
        pool: MYLAPTOP
        steps:
          - script: C:\Users\Satish\AppData\Local\UiPath\app-20.10.0-beta0149\UiRobot.exe pack $(Build.SourcesDirectory)\project.json -o $(Build.ArtifactStagingDirectory)\ -v 1.0.$(Build.BuildNumber)
            displayName: "Build the artifact"
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: drop
            
  - stage: DeployUat
    displayName: Deploy build artifact to UAT
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: deployUat
        displayName: Deploy package to UAT Orchestrator
        pool: MYLAPTOP
        environment: UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                  displayName: Download build artifact on build agent
                - powershell: |
                    Import-Module UiPath.Powershell
                    $token = Get-UiPathAuthToken -ClientId $(UATClientId) -UserKey $(UATUserKey) -AccountName $(UATAccountLogicalName) -CloudDeployment 'Production' -TenantName $(UATTenantLogicalName)
                    Add-UiPathPackage -PackageFile $(Pipeline.Workspace)\drop\UiPathAzureDevOps.1.0.$(Build.BuildNumber).nupkg -AuthToken $token